# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-20 23:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=1024)),
                ('full_name', models.CharField(max_length=1024)),
                ('score', models.IntegerField()),
                ('email', models.CharField(max_length=1024)),
                ('profile_picture_url', models.TextField()),
                ('birthday', models.DateField()),
                ('gender', models.CharField(max_length=2)),
                ('phone_number', models.CharField(max_length=20)),
                ('fb_access_token', models.TextField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
