# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-01 20:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20170522_2251'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-date_created']},
        ),
        migrations.AddField(
            model_name='user',
            name='description',
            field=models.TextField(default='', null=True),
        ),
    ]
