# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-07 14:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20170706_2055'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_link',
            field=models.CharField(default='', max_length=2048),
        ),
    ]
