# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-14 04:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_fcmtoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fcmtoken',
            name='device_token',
            field=models.TextField(blank=True, null=True),
        ),
    ]
