# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-06 20:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0004_auto_20170706_2055'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=1024)),
                ('from_timestamp', models.DateTimeField()),
                ('to_timestamp', models.DateTimeField()),
                ('price', models.DecimalField(decimal_places=10, max_digits=19)),
                ('currency', models.CharField(max_length=10)),
                ('address', models.TextField()),
                ('attending', models.IntegerField(default=1)),
                ('latitude', models.DecimalField(decimal_places=10, max_digits=19)),
                ('longitude', models.DecimalField(decimal_places=10, max_digits=19)),
                ('event_image_url', models.TextField()),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('hoster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.User')),
            ],
        ),
    ]
