# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-15 19:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_attendee'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendee',
            name='chat_notification',
            field=models.BooleanField(default=True),
        ),
    ]
