# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-16 18:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_checklistitem_item_flag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklistitem',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.User'),
        ),
    ]
