# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-05 20:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20170730_1909'),
        ('events', '0008_auto_20170716_1824'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invites',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-create_at']},
        ),
        migrations.AddField(
            model_name='invites',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invite_event', to='events.Event'),
        ),
        migrations.AddField(
            model_name='invites',
            name='sent_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invite_sent_by', to='users.User'),
        ),
        migrations.AddField(
            model_name='invites',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invite_user', to='users.User'),
        ),
    ]
