# Copyright Hostr LLC.
# GAE flexible environment runtime config
# [START runtime]
runtime: python
env: flex
entrypoint: gunicorn -b :$PORT mysite.wsgi

runtime_config:
  python_version: 2
# [END runtime]